name: SearchX Release

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    strategy:
      matrix:
        node-version: [ 14.x ]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Detect project version
        id: project_version
        run: echo "::set-output name=project_version::$(node -p "require('./package.json').version")"
        shell: bash
      - name: Current project version
        run: echo ${{ steps.project_version.outputs.project_version}}
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.project_version.outputs.project_version}}
          name: SearchX ${{ steps.project_version.outputs.project_version}}
          draft: true
          prerelease: false
          bodyFile: .github/workflows/release-note.md
          token: ${{ secrets.GITHUB_TOKEN }}
  build:
    strategy:
      matrix:
        os: [ macos-10.15, windows-2019, ubuntu-18.04 ]
        node-version: [ 14.x ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Load private files
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: src/private/StatisticsApi.js
          contents: ${{ secrets.STATISTICS_API }}
          write-mode: overwrite
      - name: Use Node.js ${{matrix.node-version}} in ${{matrix.os}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Download packages
        run: npm install
      - name: Build project
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: npm run electron:build
