name: SearchX Release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - dev-private-workflow

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-18.04 ]
        node-version: [ 14.x ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Load private files
        uses: DamianReeves/write-file-action
        with:
          path: src/private/StatisticsApi.js
          content: ${{ secrets.STATISTICS_API }}
          mode: overwrite
      - name: Show private files
        run: cat src/private/StatisticsApi.js
